Repository murramge/ArtsConnectApp, pull requests merged in 2024-05, with the labels that each got.

#84 feat:스크럼수정내용
  src/atoms/inputs/CommonInput.tsx
  src/atoms/inputs/LoginInput.tsx
  src/components/cardlist/SearchList.tsx
  src/components/inputs/SignInput.tsx
  src/components/sign/LoginView.tsx
  src/pages/Community.tsx
  src/template/Sign/sampleTemplate.tsx
  src/utils/sign.ts
Labels: feat

#94 Feature/#78 sign in sign up api
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  package-lock.json
  package.json
  react-native-config.d.ts
  src/apis/supabase/auth.ts
  src/assets/icons/kakao.png
  src/atoms/inputs/CommonInput.tsx
  src/components/inputs/SignInput.tsx
  src/components/sign/LoginView.tsx
  src/components/sign/signUpView.tsx
  src/pages/AuthHome.tsx
  src/router.tsx
  yarn.lock
Labels: feat

#103 Feature/#98 pw reset deep link
  App.tsx
  android/app/src/main/AndroidManifest.xml
  src/apis/supabase/auth.ts
  src/apis/supabase/supabase.ts
  src/components/inputs/SignInput.tsx
  src/components/sign/LoginView.tsx
  src/pages/Login.tsx
  src/router.tsx
  src/template/Sign/FindPasswordPage.tsx
  src/template/Sign/NewPasswordPage.tsx
  src/utils/sign.ts
  src/utils/validation.tsx
Labels: feat

#113 Feature/#106 step form bottom
  src/components/multistepform/MultiStepFormBottom.tsx
  src/components/tapbar/CommunityPlusButton.tsx
  src/template/Community/CommunitySelect.tsx
Labels: feat

#114 Feature/91 community select meeting date
  src/pages/communitySelect/CommunityDateSelect.tsx
Labels: feat

#119 프로필 API
  android/app/src/main/AndroidManifest.xml
  package-lock.json
  package.json
  src/apis/supabase/profile.d.ts
  src/apis/supabase/profile.ts
  src/utils/permissions.ts
  yarn.lock
Labels: feat

#127 모임 상세 화면
  src/apis/supabase/auth.ts
  src/apis/supabase/bucket.ts
  src/apis/supabase/comment.d.ts
  src/apis/supabase/comment.ts
  src/apis/supabase/meeting.d.ts
  src/apis/supabase/meeting.ts
  src/components/CommunitySelectLayOut.tsx
  src/components/carditem/CommunityCardItem.tsx
  src/pages/Community.tsx
  src/router.tsx
  src/template/Community/CommunityDetail.tsx
Labels: feat

#181 Feature seunghoon refactoring
  App.tsx
  babel.config.js
  package-lock.json
  package.json
  src/apis/supabase/auth.ts
  src/components/common/button/SearchHeaderButton.tsx
  src/components/common/header/BackHeader.tsx
  src/components/common/header/StepHeader.tsx
  src/components/common/header/TitleHeader.tsx
  src/components/common/input/SearchInput.tsx
  src/components/common/input/SignInput.tsx
  src/components/common/modals/AlramModal.tsx
  src/components/common/modals/CommunityJoinModal.tsx
  src/components/community/CommunityCardItem.tsx
  src/components/search/SearchCardItem.tsx
  src/components/signForm/LoginForm.tsx
  src/components/signForm/SignTemplate.tsx
  src/components/signForm/signUpForm.tsx
  src/hooks/useBackHandler.ts
  src/pages/Community/CommunityDetail.tsx
  src/pages/CommunitySelect/stappage/CommunityDateSelectFourStap.tsx
  src/pages/CommunitySelect/stappage/CommunityIntroduceFiveStap.tsx
  src/pages/Home/main/hooks/useDetailNavigation.ts
  src/pages/Home/search/Search.tsx
  src/pages/Home/search/SearchResultPage.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/setting/SettingsItems.tsx
  src/pages/MyPage/setting/SettingsList.tsx
  src/pages/Sign/AuthHome.tsx
  src/pages/Sign/passwordPage/FindPasswordPage.tsx
  src/pages/Sign/passwordPage/NewPasswordPage.tsx
  src/pages/Splash.tsx
  src/router.d.ts
  src/router.tsx
  src/utils/route.ts
  tsconfig.json
  yarn.lock
Labels: cleanup

#206 Feature seunghoon refactoring
  .eslintrc.js
  babel.config.js
  package-lock.json
  src/apis/supabase/meeting.d.ts
  src/apis/supabase/meeting.ts
  src/atoms/buttons/TextButton.tsx
  src/components/common/CustomBottomTabBar.tsx
  src/components/common/CustomCalendar.tsx
  src/components/common/button/SearchHeaderButton.tsx
  src/components/common/cardlist/HorizontalCardList.tsx
  src/components/common/header/BackHeader.tsx
  src/components/common/header/StepHeader.tsx
  src/components/common/label/InputLabel.tsx
  src/components/common/layout/Grid.tsx
  src/components/common/modals/ConfirmModal.tsx
  src/components/common/multistepform/MultiStepFormBottom.tsx
  src/hooks/useBoxOfficeList.ts
  src/hooks/useImage.ts
  src/hooks/usePerformanceList.ts
  src/pages/Community/CommunityFilter.tsx
  src/pages/CommunitySelect/CommunitySelectLayOut.tsx
  src/pages/Home/search/SearchResultPage.tsx
  src/router.d.ts
  src/styles/common.ts
  tsconfig.json
  yarn.lock
Labels: cleanup, feat

#207 #176
  src/components/common/multistepform/MultiStepFormBottom.tsx
Labels: cleanup

#213 Profile 탭 기능 구현
  .eslintrc.js
  android/app/src/main/res/values/strings.xml
  react-native-config.d.ts
  src/apis/supabase/profile.d.ts
  src/components/mypage/MyPageEditHeader.tsx
  src/components/mypage/MyPageMainHeader.tsx
  src/pages/Home/detail/Detail.tsx
  src/pages/MyPage/ProfileEdit.tsx
  src/pages/MyPage/hooks/useProfileApi.ts
  src/utils/validation.tsx
  yarn.lock
Labels: feat

#220 Feature seunghoon refactoring
  package-lock.json
  src/apis/supabase/meeting.ts
  src/components/common/header/BackHeader.tsx
  src/components/common/header/SearchHeader.tsx
  src/components/community/CommunityTabBar.tsx
  src/pages/Community/Community.tsx
  src/pages/Community/CommunityFilter.tsx
  src/pages/Community/hooks/useMettingApi.tsx
  src/pages/CommunitySelect/CommunitySelectLayOut.tsx
  src/pages/MyPage/hooks/useProfileApi.ts
Labels: feat

#221 #161, #189, #222
  App.tsx
  package-lock.json
  package.json
  src/apis/supabase/auth.ts
  src/apis/supabase/meeting.d.ts
  src/apis/supabase/meeting.ts
  src/apis/supabase/supabase.ts
  src/components/common/header/StepHeader.tsx
  src/components/common/modals/CalendarModal.tsx
  src/components/common/modals/CommunityQuitModal.tsx
  src/components/common/multistepform/MultiStepFormBottom.tsx
  src/pages/Community/CommunityDetail.tsx
  src/pages/CommunitySelect/CommunitySelectLayOut.tsx
  src/pages/CommunitySelect/steppage/CommunityFiveStep.tsx
  src/pages/CommunitySelect/steppage/CommunityFourStep.tsx
  src/pages/CommunitySelect/steppage/CommunityLastStep.tsx
  src/pages/CommunitySelect/steppage/CommunityThreeStep.tsx
  src/pages/Home/detail/Detail.tsx
  src/pages/Sign/passwordPage/NewPasswordPage.tsx
  src/router.d.ts
  yarn.lock
Labels: feat

#234 Feature seunghoon refactoring
  src/apis/supabase/comment.ts
  src/apis/supabase/meeting.ts
  src/components/common/cardlist/HorizontalCardList.tsx
  src/components/community/CommunityCardItem.tsx
  src/components/community/CommunityTabBar.tsx
  src/pages/Community/Community.tsx
  src/pages/Community/hooks/useMeetingApi.tsx
  src/pages/Community/hooks/useMettingApi.tsx
  src/pages/MyPage/ProfileEdit.tsx
Labels: feat

#237 Feature seunghoon refactoring
  __tests__/kopis.test.ts
  src/apis/kopis.d.ts
  src/apis/kopis.ts
  src/components/common/cardlist/HorizontalCardList.tsx
  src/components/common/image/ProfileImage.tsx
  src/components/common/modals/CommentsModal.tsx
  src/components/common/modals/CommunityJoinModal.tsx
  src/components/community/CommunityCreate.tsx
  src/components/community/CommunityFilterBar.tsx
  src/components/community/CommunityTabBar.tsx
  src/components/mypage/MyPageEditHeader.tsx
  src/components/mypage/MyPageMainHeader.tsx
  src/pages/Community/Community.tsx
  src/pages/Community/CommunityDetail.tsx
  src/pages/Community/CommunityFilter.tsx
  src/pages/Community/hooks/useMeetingApi.tsx
  src/pages/Home/booking/Booking.tsx
  src/pages/Home/detail/hooks/usePerformanceDetailApi.tsx
  src/pages/MyPage/ProfileEdit.tsx
  src/pages/Sign/passwordPage/FindPasswordPage.tsx
Labels: feat

#249 Feature seunghoon refactoring
  src/apis/supabase/auth.ts
  src/components/common/CustomBottomTabBar.tsx
  src/components/mypage/MyPageMainList.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/ProfileEdit.tsx
  src/pages/MyPage/hooks/useUserMettingsApi.ts
  src/pages/MyPage/setting/SettingsList.tsx
  src/pages/Sign/AuthHome.tsx
  src/router.d.ts
Labels: feat

#261 Feature seunghoon refactoring
  App.tsx
  android/app/src/main/java/com/proto/MainApplication.kt
  package-lock.json
  package.json
  react-native-config.d.ts
  src/apis/rollbar.ts
  src/components/common/modals/CommunityJoinModal.tsx
  src/pages/Community/CommunityDetail.tsx
  src/pages/MyPage/setting/SettingsList.tsx
  yarn.lock
Labels: feat

#269 Feature seunghoon refactoring
  android/app/proguard-rules.pro
  android/app/src/main/java/com/gonggamapply/MainActivity.kt
  android/app/src/main/java/com/gonggamapply/MainApplication.kt
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/ic_launcher_background.xml
  android/app/src/main/res/values/strings.xml
  android/settings.gradle
  app.json
  src/apis/supabase/auth.ts
  src/components/common/cardlist/HorizontalCardList.tsx
  src/components/community/CommunityCreate.tsx
  src/pages/Home/detail/Detail.tsx
  src/pages/Home/search/SearchResultPage.tsx
  src/pages/Sign/AuthHome.tsx
Labels: feat

#275 Feature seunghoon refactoring
  android/app/build.gradle
  src/atoms/inputs/CommonInput.tsx
  src/components/common/header/SearchHeader.tsx
  src/components/common/input/SearchInput.tsx
  src/components/mypage/MyPageMainList.tsx
  src/pages/Community/Community.tsx
  src/pages/Community/CommunityDetail.tsx
  src/pages/MyPage/setting/SettingsList.tsx
Labels: fix, feat

#278 Feature seunghoon refactoring
  android/app/build.gradle
  android/app/src/main/java/com/gonggamapply/KeyUtilsModule.kt
  android/app/src/main/java/com/gonggamapply/KeyUtilsPackage.kt
  android/app/src/main/java/com/gonggamapply/MainApplication.kt
  package.json
  src/KeyUtilsModule/KeyUtilsModule.d.ts
  src/KeyUtilsModule/KeyUtilsModule.ts
  src/components/common/cardlist/HorizontalCardList.tsx
  src/components/common/input/SearchInput.tsx
  src/components/common/modals/CommentsModal.tsx
  src/components/community/CommunityCardItem.tsx
  src/components/detail/DetailPageMap.tsx
  src/pages/Community/Community.tsx
  src/pages/Community/hooks/useMeetingApi.tsx
  src/pages/CommunitySelect/steppage/CommunityLastStep.tsx
  src/pages/CommunitySelect/steppage/CommunityTwoStep.tsx
  src/pages/Home/main/Home.tsx
  src/pages/MyPage/setting/SettingsList.tsx
  src/pages/Sign/passwordPage/NewPasswordPage.tsx
Labels: feat
