Repository murramge/ArtsConnectApp, pull requests merged in 2024-04, with the labels that each got.

#7 공연 공공 데이터(KOPIS) API
  .gitignore
  __tests__/kopisApi.test.ts
  babel.config.js
  package-lock.json
  package.json
  react-native-config.d.ts
  src/apis/axios.ts
  src/apis/kopis.ts
  src/interfaces/kopis.interface.ts
  tsconfig.json
  yarn.lock
Labels: feat

#18 Feature/#13 main bottom card
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  package-lock.json
  package.json
  react-native-config.d.ts
  src/apis/kopis.ts
  src/assets/images/main/artBg.png
  src/components/ArtItem.tsx
  src/components/ArtList.tsx
  src/pages/Home.tsx
  src/styles/color.ts
  yarn.lock
Labels: chore, feat

#20 Feature/#9 CustomBottomTabBar
  src/components/CustomBottomTabBar.tsx
  src/router.tsx
Labels: feat

#25 Feature/#11 authapi
  __tests__/auth.test.ts
  react-native-config.d.ts
  src/apis/dummy.tsx
  src/apis/supabase/auth.d.ts
  src/apis/supabase/auth.ts
  src/apis/supabase/supabase.ts
Labels: feat

#36 공연 검색에 장르, 지역 필터 추가
  src/pages/PerformanceSearch.tsx
Labels: feat

#38 BottomTab에 Calendar탭 추가
  src/components/CustomBottomTabBar.tsx
  src/router.tsx
Labels: feat

#40 공연 시설 상세 조회 API 추가
  __tests__/kopis.test.ts
  src/apis/kopis.d.ts
  src/apis/kopis.ts
  src/components/cardlist/ArtList.tsx
  src/components/cardlist/MainUpperCardBar.tsx
  src/components/categories/MainCategories.tsx
  src/template/home/DetailPage.tsx
  src/template/home/HomeTemplates.tsx
  src/utils/category.ts
Labels: refactoring, feat

#44 공연 상세 정보 이미지 배열로만 오게 수정
  src/apis/kopis.d.ts
  src/apis/kopis.ts
Labels: fix

#53 Fix image downsampling
  src/components/details/MainDetailsContent.tsx
Labels: cleanup

#54 Featur#50 detail feature
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  package-lock.json
  package.json
  src/assets/icons/location-pin.png
  src/assets/icons/theater.png
  src/atoms/buttons/CommonButton.tsx
  src/atoms/buttons/SearchHeaderButton.tsx
  src/components/carditem/ArtItem.tsx
  src/components/carditem/MainUpperCard.tsx
  src/components/cardlist/MainUpperCardBar.tsx
  src/components/details/MainDetailsContent.tsx
  src/components/details/MainDetailsInfo.tsx
  src/components/details/MainDetailsMap.tsx
  src/components/header/BackHeader.tsx
  src/components/header/ThumbnailHeader.tsx
  src/components/inputs/SearchInput.tsx
  src/components/inputs/SearchInputBack.tsx
  src/pages/Search.tsx
  src/router.tsx
  src/template/home/DetailPage.tsx
  src/template/home/HomeTemplates.tsx
  src/template/home/SearchPage.tsx
  yarn.lock
Labels: refactoring, feat

#55 Feature/#26 meetingapi
  __tests__/apis/kopis/kopis.test.ts
  __tests__/apis/supabase/auth.test.ts
  __tests__/apis/supabase/comment.test.ts
  __tests__/apis/supabase/meeting.test.ts
  android/app/build.gradle
  android/settings.gradle
  package-lock.json
  package.json
  src/apis/supabase/bucket.ts
  src/apis/supabase/comment.d.ts
  src/apis/supabase/comment.ts
  src/apis/supabase/meeting.d.ts
  src/apis/supabase/meeting.ts
  yarn.lock
Labels: feat

#65 Feature/#48 search page api
  src/apis/kopis.d.ts
  src/apis/kopis.ts
  src/atoms/buttons/CalendarButton.tsx
  src/atoms/buttons/CancelButton.tsx
  src/atoms/inputs/CommonInput.tsx
  src/components/carditem/SearchItem.tsx
  src/components/cardlist/SearchList.tsx
  src/components/inputs/SearchInput.tsx
  src/hooks/dummy.tsx
  src/hooks/useRecentSearch.ts
  src/pages/PerformanceSearch.tsx
  src/pages/Search.tsx
  src/router.tsx
  src/template/home/SearchResultPage.tsx
Labels: feat
